import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.or': 'or',
    'common.examples': 'Examples',

    // Navigation
    'nav.features': 'Features',
    'nav.fairs': 'Fairs',
    'nav.community': 'Community',
    'nav.examples': 'Examples',
    'nav.nosotros': 'About us',
    'nav.about': 'Who we are',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.login': 'Sign in',
    'nav.register': 'Join the community',

    // Hero (Landing)
    'hero.badge': 'Social Solidarity Economy',
    'hero.title': 'Your community, your market',
    'hero.subtitle': 'Connect with local entrepreneurs, publish your products, and participate in an economy that puts people first.',
    'hero.cta': 'Join the community',
    'hero.secondary': 'See examples',

    // How it works (Landing)
    'howItWorks.title': 'How does it work?',
    'howItWorks.subtitle': 'Three simple steps to join the movement',
    'howItWorks.step1.title': 'Create your profile',
    'howItWorks.step1.description': 'Register and set up your store in minutes with a template that fits your style and business.',
    'howItWorks.step2.title': 'Publish your products',
    'howItWorks.step2.description': 'Upload photos, descriptions, and prices. Manage your catalog easily from anywhere.',
    'howItWorks.step3.title': 'Share and sell',
    'howItWorks.step3.description': 'Share your link on WhatsApp, social media, and start receiving orders from your community.',
    'howItWorks.learnMore': 'Learn more about features',

    // Values (Landing)
    'values.title': 'Our principles',
    'values.subtitle': 'JMarkets is built on values that put people and community first',
    'values.fairTrade.title': 'Fair trade',
    'values.fairTrade.description': 'We ensure fair conditions and transparent prices for every participant in the ecosystem.',
    'values.conscious.title': 'Conscious consumption',
    'values.conscious.description': 'We promote local and sustainable purchasing decisions that benefit the whole community.',
    'values.local.title': 'Local community',
    'values.local.description': 'Every purchase strengthens the local economy and builds bonds in the neighborhood.',
    'values.transparency.title': 'Transparency',
    'values.transparency.description': 'No hidden fees, no surprises. We operate openly and honestly at every step.',

    // Final CTA
    'cta.community.title': 'Ready to join the community?',
    'cta.community.subtitle': 'Create your space for free and start selling with purpose today.',
    'cta.community.button': 'Start for free',

    // Features page
    'features.page.badge': 'Platform features',
    'features.page.title': 'Everything you need to sell with purpose',
    'features.page.subtitle': 'Simple, powerful tools designed for entrepreneurs who value community over complexity.',
    'features.templates.title': 'Design your store',
    'features.templates.description': 'Choose from professional templates adapted to your type of business. No coding needed.',
    'features.whatsapp.title': 'Sell via WhatsApp',
    'features.whatsapp.description': 'Share your catalog link and receive orders directly through WhatsApp. Fast and familiar.',
    'features.products.title': 'Product management',
    'features.products.description': 'Upload, organize, and manage your catalog easily. Photos, descriptions, prices — all in one place.',
    'features.catalog.title': 'Shareable digital catalog',
    'features.catalog.description': 'QR code and shareable link ready to share anywhere — social media, messaging apps, print.',
    'features.orders.title': 'Order tracking',
    'features.orders.description': 'Manage your orders and keep your customers informed at every step of the process.',
    'features.subdomain.title': 'Your own space online',
    'features.subdomain.description': 'Your store gets a unique address from day one — easy to share, easy to remember.',
    'features.useCases.title': 'Who uses JMarkets?',
    'features.useCases.subtitle': 'Real entrepreneurs, real stories',
    'features.useCase1.title': 'Artisan makers',
    'features.useCase1.description': 'Craft sellers who need a beautiful digital catalog to share at local markets and online.',
    'features.useCase2.title': 'Food entrepreneurs',
    'features.useCase2.description': 'Home cooks and food producers selling their products through WhatsApp and social media.',
    'features.useCase3.title': 'Local cooperatives',
    'features.useCase3.description': 'Community groups managing collective sales, barter, and shared economic projects.',
    'features.cta.title': 'Start building your space today',
    'features.cta.subtitle': 'Join thousands of entrepreneurs already selling with purpose.',
    'features.cta.button': 'Create your store for free',

    // Fairs page
    'fairs.badge': 'Active fairs',
    'fairs.title': 'Ferias: where community gathers',
    'fairs.subtitle': 'Virtual and local fairs that bring buyers and sellers together in a shared space.',
    'fairs.what.title': 'What are JMarkets fairs?',
    'fairs.what.description': 'Fairs are organized events — virtual or in-person — where multiple sellers come together in one shared space. Buyers can discover many local producers at once, and sellers gain visibility as part of a community.',
    'fairs.types.title': 'Types of fairs',
    'fairs.types.virtual.title': 'Virtual fairs',
    'fairs.types.virtual.description': 'Online events where sellers share their stores under a common theme. Promoted across the JMarkets community.',
    'fairs.types.physical.title': 'Local & physical fairs',
    'fairs.types.physical.description': 'In-person market events organized by local communities. Use JMarkets as your digital presence at the fair.',
    'fairs.types.barter.title': 'Barter & exchange fairs',
    'fairs.types.barter.description': 'Special events dedicated to swapping products or services without money. Pure Social Solidarity Economy.',
    'fairs.howJoin.title': 'How to participate',
    'fairs.howJoin.step1.title': 'Set up your store',
    'fairs.howJoin.step1.description': 'Create or update your store with your products and contact info.',
    'fairs.howJoin.step2.title': 'Register for a fair',
    'fairs.howJoin.step2.description': 'Browse upcoming fairs and apply to participate as a seller.',
    'fairs.howJoin.step3.title': 'Sell and connect',
    'fairs.howJoin.step3.description': 'Receive orders and connect with buyers and other sellers in your community.',
    'fairs.cta.title': 'Ready to show your products at a fair?',
    'fairs.cta.subtitle': 'Create your store and join the next fair in your community.',
    'fairs.cta.button': 'Join the community',

    // Community page
    'community.badge': 'Our community',
    'community.title': 'More than a store — a community',
    'community.subtitle': 'JMarkets connects people who want to trade locally, support each other, and build a fairer economy together.',
    'community.values.title': 'What we stand for',
    'community.values.subtitle': 'Six principles that guide everything we build',
    'community.values.1.title': 'Fair trade',
    'community.values.1.description': 'Fair prices and dignified conditions for every participant.',
    'community.values.2.title': 'Local production',
    'community.values.2.description': 'We celebrate what is made nearby, by real people.',
    'community.values.3.title': 'Conscious consumption',
    'community.values.3.description': 'We buy what we truly need, from people we know.',
    'community.values.4.title': 'Transparency',
    'community.values.4.description': 'No hidden costs. Open and honest at every step.',
    'community.values.5.title': 'Collaboration',
    'community.values.5.description': 'We grow together, not at each other\'s expense.',
    'community.values.6.title': 'Exchange',
    'community.values.6.description': 'Value doesn\'t always need money. Barter is welcome here.',
    'community.barter.title': 'Barter & exchange',
    'community.barter.description': 'Our barter system lets community members exchange products or services without money. Skills, time, goods — all have value.',
    'community.barter.how1': 'List what you offer',
    'community.barter.how2': 'Find what you need',
    'community.barter.how3': 'Agree and exchange',
    'community.mutual.title': 'Mutual support networks',
    'community.mutual.description': 'Connect with entrepreneurs who share your values. Find collaborators, mentors, and customers who believe in local commerce.',
    'community.stories.title': 'Real stories from our community',
    'community.stories.subtitle': 'People who changed how they sell and connect',
    'community.story1.quote': '"I started selling homemade jams and thanks to JMarkets I now have 200 loyal customers in my neighborhood."',
    'community.story1.name': 'María González',
    'community.story1.business': 'Homemade preserves · Buenos Aires',
    'community.story2.quote': '"The barter system let me exchange graphic design for legal services. That is real economy — human and fair."',
    'community.story2.name': 'Carlos Ruiz',
    'community.story2.business': 'Graphic designer · Medellín',
    'community.story3.quote': '"Our cooperative finally has a digital presence without needing a programmer or paying a fortune."',
    'community.story3.name': 'Ana Morales',
    'community.story3.business': 'Agricultural cooperative · Oaxaca',
    'community.cta.title': 'Become part of the community',
    'community.cta.subtitle': 'Create your store for free and connect with people who share your values.',
    'community.cta.button': 'Join today',

    // About / Who we are
    'about.badge': 'Who we are',
    'about.title': 'Born from community, built for community',
    'about.subtitle': 'JMarkets was born in Guápiles, Costa Rica, from a university community project during the pandemic to reconnect isolated communities through their local fairs and barter networks.',
    'about.queEs.badge': 'What is JMarkets?',
    'about.queEs.title': 'Not just a store — a movement',
    'about.queEs.description': 'JMarkets is a platform born from the TCU "Comer Orgánico" at the Universidad de Costa Rica, in partnership with the Feria del Trueque Verde Manantial in Guápiles. It lets entrepreneurs, local businesses, and communities create their own space online, publish products, sell (mainly via WhatsApp), and participate in fairs and barter — just like before the pandemic, but now with the reach of the internet.',
    'about.queEs.point1': 'Sell and exchange products in your community',
    'about.queEs.point2': 'Connect neighbors who were isolated during the pandemic',
    'about.queEs.point3': 'Participate in virtual and local fairs and barter events',
    'about.queEs.point4': 'Preserve and document community fair culture',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To give communities the digital tools to stay connected, trade fairly, and keep their local fair and barter traditions alive — no matter what the world throws at them.',
    'about.story.title': 'Our Story',
    'about.story.para1': 'JMarkets was born during the COVID-19 pandemic as part of the TCU (Trabajo Comunal Universitario) "Comer Orgánico" at the Universidad de Costa Rica. We were working alongside the Feria del Trueque Verde Manantial in Guápiles, Costa Rica — a vibrant community space where people gathered to exchange products, services, and stories.',
    'about.story.para2': 'When the pandemic hit, communities were suddenly alone and disconnected. The fairs that had brought people together for years went silent. We saw neighbors who had always found each other at the market now unable to connect — and we knew technology could help bridge that gap. So we built JMarkets: a digital recreation of the fairs that existed before, designed to let people show what they have, what they sell, and what they\'re willing to trade.',
    'about.story.para3': 'From the beginning, we documented every step of this process — the community needs, the barter dynamics, the social bonds that make a fair more than just a market. That documentation lives in JMarkets. Today, this project continues growing as a tool for any community that wants to preserve its local economy and keep its people connected.',
    'about.values.title': 'Our Values',
    'about.values.fairTrade': 'Fair Trade',
    'about.values.fairTrade.description': 'Fair prices and dignified conditions for all participants',
    'about.values.conscious': 'Conscious Consumption',
    'about.values.conscious.description': 'Promoting local and sustainable purchasing decisions',
    'about.values.local': 'Local Community',
    'about.values.local.description': 'Every purchase strengthens local economy and neighborhood bonds',
    'about.values.transparency': 'Transparency',
    'about.values.transparency.description': 'No hidden fees. Open and honest at every step.',
    'about.team.title': 'A project rooted in community',
    'about.team.description': 'JMarkets started as a university community project and grew into a platform used by real people. We are researchers, builders, and community advocates who believe that technology should serve people — not the other way around.',

    // Examples page
    'examples.badge': 'Store examples',
    'examples.title': 'Choose your style, create your space',
    'examples.subtitle': 'Explore stores created with JMarkets templates. Each one has a unique design ready to customize.',
    'examples.featured': 'Featured',
    'examples.viewStore': 'Visit store',
    'examples.cta.title': 'Ready to create your own space?',
    'examples.cta.subtitle': 'Start free, choose your template, and begin connecting with your community today.',
    'examples.cta.button': 'Create my store',
    'examples.stores.demo.title': 'JMarkets Demo',
    'examples.stores.demo.description': 'Complete example store with products, shopping cart, checkout and all platform features.',
    'examples.stores.demo.category': 'Demo',
    'examples.stores.bellaNatural.title': 'Tech Gadgets Pro',
    'examples.stores.bellaNatural.description': 'Latest electronics and tech accessories. Smartphones, laptops, tablets, and innovative gadgets for modern life.',
    'examples.stores.bellaNatural.category': 'Electronics',
    'examples.stores.glamStudio.title': 'Vintage Fashion Co',
    'examples.stores.glamStudio.description': 'Curated vintage and retro clothing collection. Unique pieces from decades past with timeless style.',
    'examples.stores.glamStudio.category': 'Fashion',
    'examples.stores.royalHair.title': 'Artisan Crafts Studio',
    'examples.stores.royalHair.description': 'Handmade crafts and DIY supplies. Knitting, painting, woodworking materials and unique handcrafted items.',
    'examples.stores.royalHair.category': 'Crafts',
    'examples.stores.skinLove.title': 'Gourmet Foods Market',
    'examples.stores.skinLove.description': 'Premium organic and specialty foods. Artisan cheeses, exotic spices, craft beverages and specialty products.',
    'examples.stores.skinLove.category': 'Food',
    'examples.stores.proNails.title': 'Fitness Equipment Hub',
    'examples.stores.proNails.description': 'Home and gym fitness equipment. Dumbbells, yoga mats, resistance bands and training accessories.',
    'examples.stores.proNails.category': 'Sports',
    'examples.stores.beautySalon.title': 'Pet Care Supplies',
    'examples.stores.beautySalon.description': 'Everything for your pets. Pet toys, grooming products, nutrition, and comfortable beds for cats and dogs.',
    'examples.stores.beautySalon.category': 'Pets',

    // Footer
    'footer.description': 'Social Solidarity Economy platform for entrepreneurs, local businesses, and organized communities.',
    'footer.product': 'Platform',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.links.features': 'Features',
    'footer.links.fairs': 'Fairs',
    'footer.links.community': 'Community',
    'footer.links.examples': 'Examples',
    'footer.links.about': 'Who we are',
    'footer.links.contact': 'Contact',
    'footer.links.blog': 'Blog',
    'footer.links.privacy': 'Privacy',
    'footer.links.terms': 'Terms',
    'footer.links.cookies': 'Cookies',
    'footer.copyright': '© 2026 JMarkets. All rights reserved.',

    // Auth
    'auth.login.title': 'JMarkets',
    'auth.login.subtitle': 'Sign in to your account',
    'auth.login.email': 'Email',
    'auth.login.emailPlaceholder': 'your@email.com',
    'auth.login.password': 'Password',
    'auth.login.passwordPlaceholder': 'Enter your password',
    'auth.login.submit': 'Sign in',
    'auth.login.submitting': 'Signing in...',
    'auth.login.forgotPassword': 'Forgot your password?',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.register': 'Register',
    'auth.login.backToHome': 'Back to home',
    'auth.login.success': 'Login successful',
    'auth.login.successDescription': 'Welcome back',
    'auth.login.error': 'Login error',
    'auth.logout': 'Logout',
    'auth.register.title': 'Create account',
    'auth.register.subtitle': 'Start creating your store today',
    'auth.register.steps.personalInfo': 'Personal Info',
    'auth.register.steps.personalInfoDesc': 'Your basic information',
    'auth.register.steps.security': 'Security',
    'auth.register.steps.securityDesc': 'Create your password',
    'auth.register.steps.verify': 'Verify',
    'auth.register.steps.verifyDesc': 'Confirm your email',
    'auth.register.firstName': 'First name',
    'auth.register.firstNamePlaceholder': 'Your name',
    'auth.register.lastName': 'Last name',
    'auth.register.lastNamePlaceholder': 'Your last name',
    'auth.register.email': 'Email',
    'auth.register.emailPlaceholder': 'your@email.com',
    'auth.register.username': 'Username',
    'auth.register.usernamePlaceholder': 'johndoe123',
    'auth.register.gender': 'Gender (optional)',
    'auth.register.gender.placeholder': 'Select your gender...',
    'auth.register.gender.male': 'Male',
    'auth.register.gender.female': 'Female',
    'auth.register.gender.other': 'Other',
    'auth.register.gender.otherPlaceholder': 'Please specify...',
    'auth.register.gender.preferNotToSay': 'Prefer not to say',
    'auth.register.password': 'Password',
    'auth.register.passwordPlaceholder': 'Create a password',
    'auth.register.confirmPassword': 'Confirm password',
    'auth.register.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.register.continue': 'Continue',
    'auth.register.back': 'Back',
    'auth.register.createAccount': 'Create account',
    'auth.register.submit': 'Create account',
    'auth.register.submitting': 'Creating account...',
    'auth.register.hasAccount': 'Already have an account?',
    'auth.register.signIn': 'Sign in',
    'auth.register.login': 'Sign in',
    'auth.register.backToHome': 'Back to home',
    'auth.register.success': 'Account created',
    'auth.register.successDescription': 'Check your email to verify your account',
    'auth.register.complete': 'Registration complete',
    'auth.register.completeDescription': 'Your account is ready to use',
    'auth.register.completeStep1': 'Please complete step 1 first',
    'auth.register.error': 'Error creating account',
    'auth.register.passwordMismatch': 'Passwords do not match',
    'auth.register.passwordRequirements.minLength': 'Minimum 8 characters',
    'auth.register.passwordRequirements.lowercase': 'One lowercase letter',
    'auth.register.passwordRequirements.uppercase': 'One uppercase letter',
    'auth.register.passwordRequirements.number': 'One number',
    'auth.register.passwordRequirements.special': 'One special character',
    'auth.register.passwordStrength.label': 'Password Strength',
    'auth.register.passwordStrength.weak': 'Weak',
    'auth.register.passwordStrength.fair': 'Fair',
    'auth.register.passwordStrength.good': 'Good',
    'auth.register.passwordStrength.strong': 'Strong',
    'auth.register.passwordStrength.excellent': 'Excellent',
    'auth.forgotPassword.title': 'Forgot your password?',
    'auth.forgotPassword.subtitle': "Enter your email and we'll send you a recovery code",
    'auth.forgotPassword.email': 'Email',
    'auth.forgotPassword.emailPlaceholder': 'your@email.com',
    'auth.forgotPassword.submit': 'Send code',
    'auth.forgotPassword.submitting': 'Sending...',
    'auth.forgotPassword.backToLogin': 'Back to sign in',
    'auth.forgotPassword.success': 'Code sent',
    'auth.forgotPassword.successDescription': 'Check your email for the recovery code',
    'auth.forgotPassword.error': 'Error sending code',
    'auth.forgotPassword.checkEmail.title': 'Check your email',
    'auth.forgotPassword.checkEmail.subtitle': "We've sent a recovery code to",
    'auth.forgotPassword.checkEmail.enterCode': 'Enter code',
    'auth.forgotPassword.checkEmail.differentEmail': 'Use different email',
    'auth.resetPassword.title': 'Reset password',
    'auth.resetPassword.subtitle': 'Enter the code from your email and your new password',
    'auth.resetPassword.email': 'Email',
    'auth.resetPassword.emailPlaceholder': 'your@email.com',
    'auth.resetPassword.code': 'Recovery code',
    'auth.resetPassword.codePlaceholder': 'Enter 6-digit code',
    'auth.resetPassword.newPassword': 'New password',
    'auth.resetPassword.newPasswordPlaceholder': 'Enter your new password',
    'auth.resetPassword.confirmPassword': 'Confirm password',
    'auth.resetPassword.confirmPasswordPlaceholder': 'Confirm your new password',
    'auth.resetPassword.submit': 'Reset password',
    'auth.resetPassword.submitting': 'Resetting...',
    'auth.resetPassword.requestNewCode': 'Request new code',
    'auth.resetPassword.backToHome': 'Back to home',
    'auth.resetPassword.success': 'Password reset',
    'auth.resetPassword.successDescription': 'You can now sign in with your new password',
    'auth.resetPassword.error': 'Error resetting password',
    'auth.resetPassword.invalidCode': 'Invalid code',
    'auth.resetPassword.invalidCodeDescription': 'The code you entered is incorrect',
    'auth.resetPassword.expiredCode': 'Code expired',
    'auth.resetPassword.expiredCodeDescription': 'Please request a new code',
    'auth.verifyEmail.title': 'Verify your Email',
    'auth.verifyEmail.subtitle': 'We have sent a 6-digit code to',
    'auth.verifyEmail.code': 'Verification code',
    'auth.verifyEmail.submit': 'Verify Email',
    'auth.verifyEmail.submitting': 'Verifying...',
    'auth.verifyEmail.resendCode': 'Resend code',
    'auth.verifyEmail.resending': 'Resending...',
    'auth.verifyEmail.didntReceive': "Didn't receive the code?",
    'auth.verifyEmail.success': 'Email verified',
    'auth.verifyEmail.successDescription': 'Your account has been verified successfully',
    'auth.verifyEmail.error': 'Verification error',
    'auth.verifyEmail.resendSuccess': 'Code resent',
    'auth.verifyEmail.resendSuccessDescription': 'We have sent a new verification code',
    'auth.verifyEmail.invalidCode': 'Invalid code',
    'auth.verifyEmail.invalidCodeDescription': 'Please enter the 6-digit code',
    'auth.verifyEmail.incorrectCode': 'Incorrect code',
    'auth.verifyEmail.incorrectCodeDescription': 'The code entered is not valid',
    'auth.verifyEmail.expiredCode': 'Code expired',
    'auth.verifyEmail.expiredCodeDescription': 'The code has expired, request a new one',
    'auth.verifyEmail.resendError': 'Error',
    'auth.verifyEmail.resendErrorDescription': 'Could not resend code',
    'auth.verifyEmail.backToRegister': 'Back to registration',
    'auth.verifyEmail.alreadyVerified': 'Email already verified',
    'auth.verifyEmail.alreadyVerifiedDescription': 'Your email is already verified. You can now login.',

    // Organizations
    'organizations.create.title': 'Create your organization',
    'organizations.create.subtitle': 'Set up your store in minutes',
    'organizations.create.name': 'Store name',
    'organizations.create.namePlaceholder': 'My Store',
    'organizations.create.nameDescription': 'The public name of your store',
    'organizations.create.slug': 'Store URL',
    'organizations.create.slugPlaceholder': 'my-store',
    'organizations.create.slugDescription': 'The unique URL of your store',
    'organizations.create.subdomain': 'Subdomain',
    'organizations.create.subdomainDescription': 'Your store will be available at',
    'organizations.create.submit': 'Create store',
    'organizations.create.submitting': 'Creating store...',
    'organizations.create.success': 'Store created',
    'organizations.create.successDescription': 'Your store is ready',
    'organizations.create.error': 'Error creating store',
    'organizations.create.errorAuth': 'You must be logged in to create an organization',
    'organizations.create.slugTaken': 'This URL is already in use',
    'organizations.create.subdomainTaken': 'This subdomain is already in use',
    'organizations.create.checking': 'Checking availability...',
    'organizations.select.title': 'Select your organization',
    'organizations.select.subtitle': 'Choose the store you want to manage',
    'organizations.select.createNew': 'Create new store',
    'organizations.select.noOrganizations': 'You have no organizations',
    'organizations.select.noOrganizationsDescription': 'Create your first store to get started',
    'organizations.select.loading': 'Loading organizations...',
    'organizations.select.visitStore': 'Visit store',
    'organizations.select.manage': 'Manage',
    'organizations.select.error': 'Could not load your organizations. Please try again.',
    'organizations.select.tryAgain': 'Try Again',
    'organizations.select.pendingMessage': 'Complete the provisioning of pending organizations before creating a new one.',
    'organizations.select.statusActive': 'Active',
    'organizations.select.statusPending': 'Pending',
    'organizations.select.statusProvisioning': 'Provisioning...',
    'organizations.select.statusFailed': 'Failed',
    'organizations.select.openOrganization': 'Open Organization',
    'organizations.select.provisionInfrastructure': 'Provision Infrastructure',
    'organizations.select.retryProvisioning': 'Retry Provisioning',
    'organizations.select.infrastructureProvisioning': 'Infrastructure is being provisioned...',

    // Theme / Language
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'language.es': 'Español',
    'language.en': 'English',

    // Blog
    'blog.badge': 'Blog',
    'blog.title': 'Latest news and updates',
    'blog.subtitle': 'Tips, guides, and insights for growing your online business',
    'blog.featured': 'Featured Article',
    'blog.readMore': 'Read More',
    'blog.posted': 'Posted',
    'blog.latestArticles': 'Latest Articles',
    'blog.stayUpdated': 'Stay Updated',
    'blog.newsletter': 'Subscribe to our newsletter and get the latest articles, tips, and updates delivered to your inbox.',
    'blog.subscribe': 'Subscribe',
    'blog.privacyNote': 'We respect your privacy. Unsubscribe at any time.',
    'blog.article1.title': 'How Barter Brought a Community Back Together After the Pandemic',
    'blog.article1.excerpt': 'The story of the Feria del Trueque Verde Manantial in Guápiles — and how going digital helped neighbors reconnect when in-person fairs were impossible.',
    'blog.article1.author': 'Equipo JMarkets',
    'blog.article1.date': 'January 15, 2026',
    'blog.article2.title': 'What is Social and Solidarity Economy?',
    'blog.article2.excerpt': 'An introduction to the principles of fair trade, conscious consumption, and local community building that inspire everything we do at JMarkets.',
    'blog.article2.author': 'TCU Comer Orgánico',
    'blog.article2.date': 'January 10, 2026',
    'blog.article3.title': 'How to Set Up Your Community Space on JMarkets',
    'blog.article3.excerpt': 'A step-by-step guide to creating your profile, publishing your products or services, and connecting with your local community.',
    'blog.article3.author': 'Equipo JMarkets',
    'blog.article3.date': 'January 5, 2026',
    'blog.article4.title': 'Barter 101: How to Make Your First Trueque',
    'blog.article4.excerpt': 'Everything you need to know to propose, negotiate, and complete a fair exchange with another community member on the platform.',
    'blog.article4.author': 'Feria Verde Manantial',
    'blog.article4.date': 'December 28, 2025',
    'blog.article5.title': 'Local Fairs as Community Infrastructure',
    'blog.article5.excerpt': 'Why community fairs are more than just markets — they are spaces for social connection, knowledge sharing, and economic resilience.',
    'blog.article5.author': 'UCR TCU',
    'blog.article5.date': 'December 20, 2025',
    'blog.article6.title': 'Selling via WhatsApp: Tips for Local Entrepreneurs',
    'blog.article6.excerpt': 'Practical advice for managing orders, communicating with buyers, and building trust through WhatsApp — the most-used channel in our community.',
    'blog.article6.author': 'Equipo JMarkets',
    'blog.article6.date': 'December 12, 2025',

    // Contact
    'contact.badge': 'Contact Us',
    'contact.title': 'Get in touch',
    'contact.subtitle': "We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.address': 'Address',
    'contact.sendMessage': 'Send us a message',
    'contact.namePlaceholder': 'John Doe',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.subjectPlaceholder': 'How can we help?',
    'contact.messagePlaceholder': 'Your message here...',
    'contact.tryAgain': 'Please try again.',
    'contact.otherWays': 'Other ways to reach us',
    'contact.responseTime': 'Response Time',
    'contact.responseTimeDesc': 'We typically respond to all inquiries within 24 hours during business days. Thank you for your patience!',

    // Terms
    'terms.badge': 'Terms of Service',
    'terms.title': 'Terms and Conditions',
    'terms.subtitle': 'Please read these terms carefully before using our community platform',
    'terms.lastUpdated': 'Last updated',
    'terms.section.acceptance': '1. Acceptance of Terms',
    'terms.section.accounts': '2. User Accounts',
    'terms.section.services': '3. Platform Description',
    'terms.section.payment': '4. Community Participation',
    'terms.section.intellectual': '5. Intellectual Property',
    'terms.section.liability': '6. Limitation of Liability',
    'terms.section.changes': '7. Changes to Terms',
    'terms.section.contact': '8. Contact Information',
    'terms.acceptance.content': 'By accessing and using JMarkets, you accept and agree to be bound by these terms. JMarkets is a Social Solidarity Economy platform born from the TCU "Comer Orgánico" at the Universidad de Costa Rica. If you do not agree with these terms, please do not use this platform.',
    'terms.accounts.content': 'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to use the platform in a respectful manner consistent with the values of the community: fair trade, transparency, and solidarity.',
    'terms.services.content': 'JMarkets provides a digital platform for community fairs, local trade, and barter (trueque). Users can create their own space, publish products and services, connect with their community, and participate in virtual or local fairs. The platform was designed to preserve and extend the culture of community fairs like the Feria del Trueque Verde Manantial in Guápiles, Costa Rica.',
    'terms.payment.content': 'JMarkets is a community platform. Any transactions, exchanges, or barter agreements made between users are the responsibility of the parties involved. JMarkets acts as a facilitator and does not intervene in private transactions between community members. Users are encouraged to operate under the principles of fair trade and honest exchange.',
    'terms.intellectual.content': 'Content published by users on JMarkets remains the property of each user. The JMarkets platform itself — produced as part of the TCU "Comer Orgánico" at the Universidad de Costa Rica — is protected under applicable intellectual property laws. Users grant JMarkets a non-exclusive license to display their content within the platform.',
    'terms.liability.content': 'JMarkets is provided as a community tool on an "as is" basis. We are not responsible for the content, products, or services offered by individual users. Transactions and agreements between community members are the sole responsibility of the parties involved. We encourage all users to interact with honesty and respect.',
    'terms.changes.content': 'JMarkets reserves the right to update these terms at any time. Users will be notified of significant changes via email or a prominent notice on the platform. Continued use of the platform after changes constitutes acceptance of the new terms.',
    'terms.contact.content': 'If you have any questions about these terms, please contact us at hola@jmarkets.com or visit our contact page.',
    'terms.lastUpdatedDate': 'March 1, 2026',
    'terms.importantNotice': 'Community Commitment',
    'terms.acceptanceNotice': 'By using JMarkets, you commit to participating in the community with respect, honesty, and solidarity. This platform was built to reconnect communities — we ask every user to honor that spirit in every interaction.',

    // Privacy
    'privacy.badge': 'Privacy Policy',
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'How we collect, use, and protect your information',
    'privacy.lastUpdated': 'Last updated',
    'privacy.section.information': '1. Information We Collect',
    'privacy.section.usage': '2. How We Use Your Information',
    'privacy.section.storage': '3. Data Storage and Security',
    'privacy.section.cookies': '4. Cookies and Tracking',
    'privacy.section.third': '5. Third-Party Services',
    'privacy.section.rights': '6. Your Rights',
    'privacy.section.protection': '7. Data Protection',
    'privacy.section.contact': '8. Contact Information',
    'privacy.information.content': 'We collect information you provide directly to us, such as when you create an account, make a purchase, or contact us. This includes your name, email address, password, and payment information. We also collect information automatically when you use our platform, including log data, cookies, and device information.',
    'privacy.usage.content': 'We use your information to provide, maintain, and improve our services, process transactions, send transactional and promotional emails, respond to your inquiries, and comply with legal obligations. We use analytics data to understand how users interact with our platform and to optimize the user experience.',
    'privacy.storage.content': 'Your data is stored on secure servers with encryption technology. We implement appropriate physical, electronic, and procedural safeguards to protect your information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet is completely secure.',
    'privacy.cookies.content': 'We use cookies and similar tracking technologies to track activity on our platform and hold certain information. You can instruct your browser to refuse all cookies or to alert you when cookies are being sent. However, some features of the platform may not function properly without cookies.',
    'privacy.third.content': 'We may share your information with third-party service providers who assist us in operating our platform and conducting our business. These providers are contractually obligated to use your information only as necessary to provide services to us.',
    'privacy.rights.content': 'Depending on your location, you may have certain rights regarding your personal data, including the right to access, correct, delete, or port your information. To exercise any of these rights, please contact us at privacy@jmarkets.com.',
    'privacy.protection.content': 'We comply with applicable data protection regulations, including GDPR and similar laws. We maintain appropriate safeguards to protect your data and only retain information for as long as necessary to provide our services and comply with legal obligations.',
    'privacy.contact.content': 'If you have questions about this privacy policy or our privacy practices, please contact us at privacy@jmarkets.com or visit our contact page. We are committed to working with you to resolve any privacy concerns.',
    'privacy.lastUpdatedDate': 'January 1, 2026',
    'privacy.notice': 'Your Privacy Matters',
    'privacy.noticeDesc': "We are committed to protecting your privacy and ensuring you have a positive experience on our platform. If you have any questions about how we handle your data, please don't hesitate to contact us.",

    // Cookies
    'cookies.badge': 'Cookie Policy',
    'cookies.title': 'Cookie Policy',
    'cookies.subtitle': 'Information about how we use cookies',
    'cookies.what': 'What are Cookies?',
    'cookies.types': 'Types of Cookies',
    'cookies.essential': 'Essential Cookies',
    'cookies.essential.description': 'Necessary for basic functionality',
    'cookies.analytics': 'Analytics Cookies',
    'cookies.analytics.description': 'Help us understand how you use our platform',
    'cookies.marketing': 'Marketing Cookies',
    'cookies.marketing.description': 'Used to personalize content and ads',
    'cookies.preferences': 'Preference Cookies',
    'cookies.preferences.description': 'Remember your choices and settings',
    'cookies.manage': 'Manage Cookie Preferences',
    'cookies.explanation': 'Cookies are small text files that are stored on your device when you visit a website. They help websites remember information about your visit, such as your preferences and activity. Cookies can be essential for basic website functionality or used to enhance user experience through tracking and personalization.',
    'cookies.browser': 'Most web browsers allow you to control cookies through their settings. You can choose to accept all cookies, reject all cookies, or be notified when a cookie is being set.',
    'cookies.usingBrowser': 'Using Your Browser',
    'cookies.usingBrowserDesc': 'Most modern browsers include cookie management tools in their settings. You can typically find these under "Privacy" or "Security" settings. Different browsers (Chrome, Firefox, Safari, Edge) have different processes, but all allow you to view, delete, and manage cookies.',
    'cookies.consent': 'Cookie Consent',
    'cookies.consentDesc': 'When you first visit JMarkets, we display a cookie consent banner. You can accept all cookies, reject non-essential cookies, or customize your preferences. You can change your cookie preferences at any time through your account settings.',
    'cookies.third': 'Third-Party Cookies',
    'cookies.thirdDesc': "Some cookies may be set by third-party services (like analytics providers). These services have their own privacy policies and cookie management options. You can often manage these preferences through the third-party's website.",
    'cookies.important': 'Important Note',
    'cookies.importantDesc': 'Disabling essential cookies may affect the functionality of our platform. We recommend keeping essential cookies enabled to ensure the best experience. Non-essential cookies can be disabled without affecting core functionality.',
  },

  es: {
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.submit': 'Enviar',
    'common.or': 'o',
    'common.examples': 'Ejemplos',

    // Navegación
    'nav.features': 'Funcionalidades',
    'nav.fairs': 'Ferias',
    'nav.community': 'Comunidad',
    'nav.examples': 'Ejemplos',
    'nav.nosotros': 'Nosotros',
    'nav.about': 'Quiénes somos',
    'nav.contact': 'Contacto',
    'nav.blog': 'Blog',
    'nav.login': 'Iniciar sesión',
    'nav.register': 'Únete a la comunidad',

    // Hero (Landing)
    'hero.badge': 'Economía Social Solidaria',
    'hero.title': 'Tu comunidad, tu mercado',
    'hero.subtitle': 'Conecta con emprendedores locales, publica tus productos y participa en una economía que pone a las personas primero.',
    'hero.cta': 'Únete a la comunidad',
    'hero.secondary': 'Ver ejemplos',

    // Cómo funciona (Landing)
    'howItWorks.title': '¿Cómo funciona?',
    'howItWorks.subtitle': 'Tres pasos simples para unirte al movimiento',
    'howItWorks.step1.title': 'Crea tu perfil',
    'howItWorks.step1.description': 'Regístrate y configura tu tienda en minutos con una plantilla que se adapte a tu estilo y negocio.',
    'howItWorks.step2.title': 'Publica tus productos',
    'howItWorks.step2.description': 'Sube fotos, descripciones y precios. Gestiona tu catálogo fácilmente desde cualquier lugar.',
    'howItWorks.step3.title': 'Comparte y vende',
    'howItWorks.step3.description': 'Comparte tu enlace por WhatsApp, redes sociales y empieza a recibir pedidos de tu comunidad.',
    'howItWorks.learnMore': 'Ver todas las funcionalidades',

    // Valores (Landing)
    'values.title': 'Nuestros principios',
    'values.subtitle': 'JMarkets está construido sobre valores que ponen a las personas y la comunidad primero',
    'values.fairTrade.title': 'Comercio justo',
    'values.fairTrade.description': 'Garantizamos condiciones justas y precios transparentes para todos los participantes del ecosistema.',
    'values.conscious.title': 'Consumo consciente',
    'values.conscious.description': 'Promovemos decisiones de compra locales y sostenibles que benefician a toda la comunidad.',
    'values.local.title': 'Comunidad local',
    'values.local.description': 'Cada compra fortalece la economía local y construye lazos en el barrio.',
    'values.transparency.title': 'Transparencia',
    'values.transparency.description': 'Sin cargos ocultos, sin sorpresas. Operamos de forma abierta y honesta en cada paso.',

    // CTA final
    'cta.community.title': '¿Listo para unirte a la comunidad?',
    'cta.community.subtitle': 'Crea tu espacio gratis y empieza a vender con propósito hoy.',
    'cta.community.button': 'Empezar gratis',

    // Página de Funcionalidades
    'features.page.badge': 'Funcionalidades de la plataforma',
    'features.page.title': 'Todo lo que necesitas para vender con propósito',
    'features.page.subtitle': 'Herramientas simples y poderosas diseñadas para emprendedores que valoran la comunidad sobre la complejidad.',
    'features.templates.title': 'Diseña tu tienda',
    'features.templates.description': 'Elige entre plantillas profesionales adaptadas a tu tipo de negocio. Sin programación.',
    'features.whatsapp.title': 'Vende por WhatsApp',
    'features.whatsapp.description': 'Comparte el enlace de tu catálogo y recibe pedidos directamente por WhatsApp. Rápido y familiar.',
    'features.products.title': 'Gestión de productos',
    'features.products.description': 'Sube, organiza y gestiona tu catálogo fácilmente. Fotos, descripciones, precios — todo en un lugar.',
    'features.catalog.title': 'Catálogo digital compartible',
    'features.catalog.description': 'Código QR y enlace compartible listo para usar en cualquier lugar — redes sociales, apps de mensajería, impreso.',
    'features.orders.title': 'Seguimiento de pedidos',
    'features.orders.description': 'Gestiona tus pedidos y mantén informados a tus clientes en cada paso del proceso.',
    'features.subdomain.title': 'Tu propio espacio en línea',
    'features.subdomain.description': 'Tu tienda tiene una dirección única desde el primer día — fácil de compartir, fácil de recordar.',
    'features.useCases.title': '¿Quién usa JMarkets?',
    'features.useCases.subtitle': 'Emprendedores reales, historias reales',
    'features.useCase1.title': 'Artesanos y makers',
    'features.useCase1.description': 'Vendedores de artesanías que necesitan un catálogo digital bonito para compartir en ferias locales y en línea.',
    'features.useCase2.title': 'Emprendedores de alimentos',
    'features.useCase2.description': 'Cocineros caseros y productores de alimentos que venden sus productos por WhatsApp y redes sociales.',
    'features.useCase3.title': 'Cooperativas locales',
    'features.useCase3.description': 'Grupos comunitarios que gestionan ventas colectivas, trueque y proyectos económicos compartidos.',
    'features.cta.title': 'Empieza a construir tu espacio hoy',
    'features.cta.subtitle': 'Únete a miles de emprendedores que ya venden con propósito.',
    'features.cta.button': 'Crear tu tienda gratis',

    // Página de Ferias
    'fairs.badge': 'Ferias activas',
    'fairs.title': 'Ferias: donde la comunidad se reúne',
    'fairs.subtitle': 'Ferias virtuales y presenciales que conectan compradores y vendedores en un espacio compartido.',
    'fairs.what.title': '¿Qué son las ferias de JMarkets?',
    'fairs.what.description': 'Las ferias son eventos organizados — virtuales o presenciales — donde múltiples vendedores se reúnen en un espacio compartido. Los compradores pueden descubrir muchos productores locales a la vez, y los vendedores ganan visibilidad como parte de una comunidad.',
    'fairs.types.title': 'Tipos de ferias',
    'fairs.types.virtual.title': 'Ferias virtuales',
    'fairs.types.virtual.description': 'Eventos en línea donde los vendedores comparten sus tiendas bajo un tema común. Promovidos en toda la comunidad JMarkets.',
    'fairs.types.physical.title': 'Ferias locales y presenciales',
    'fairs.types.physical.description': 'Eventos de mercado presencial organizados por comunidades locales. Usa JMarkets como tu presencia digital en la feria.',
    'fairs.types.barter.title': 'Ferias de trueque e intercambio',
    'fairs.types.barter.description': 'Eventos especiales dedicados al intercambio de productos o servicios sin dinero. Economía Social Solidaria pura.',
    'fairs.howJoin.title': 'Cómo participar',
    'fairs.howJoin.step1.title': 'Configura tu tienda',
    'fairs.howJoin.step1.description': 'Crea o actualiza tu tienda con tus productos e información de contacto.',
    'fairs.howJoin.step2.title': 'Inscríbete en una feria',
    'fairs.howJoin.step2.description': 'Explora las próximas ferias y solicita participar como vendedor.',
    'fairs.howJoin.step3.title': 'Vende y conecta',
    'fairs.howJoin.step3.description': 'Recibe pedidos y conecta con compradores y otros vendedores de tu comunidad.',
    'fairs.cta.title': '¿Listo para mostrar tus productos en una feria?',
    'fairs.cta.subtitle': 'Crea tu tienda y únete a la próxima feria de tu comunidad.',
    'fairs.cta.button': 'Únete a la comunidad',

    // Página de Comunidad
    'community.badge': 'Nuestra comunidad',
    'community.title': 'Más que una tienda — una comunidad',
    'community.subtitle': 'JMarkets conecta personas que quieren comerciar localmente, apoyarse mutuamente y construir juntos una economía más justa.',
    'community.values.title': 'Lo que nos guía',
    'community.values.subtitle': 'Seis principios que guían todo lo que construimos',
    'community.values.1.title': 'Comercio justo',
    'community.values.1.description': 'Precios justos y condiciones dignas para cada participante.',
    'community.values.2.title': 'Producción local',
    'community.values.2.description': 'Celebramos lo que se hace cerca, por personas reales.',
    'community.values.3.title': 'Consumo consciente',
    'community.values.3.description': 'Compramos lo que realmente necesitamos, de personas que conocemos.',
    'community.values.4.title': 'Transparencia',
    'community.values.4.description': 'Sin costos ocultos. Abiertos y honestos en cada paso.',
    'community.values.5.title': 'Colaboración',
    'community.values.5.description': 'Crecemos juntos, no a expensas del otro.',
    'community.values.6.title': 'Intercambio',
    'community.values.6.description': 'El valor no siempre necesita dinero. El trueque es bienvenido aquí.',
    'community.barter.title': 'Trueque e intercambio',
    'community.barter.description': 'Nuestro sistema de trueque permite a los miembros de la comunidad intercambiar productos o servicios sin dinero. Habilidades, tiempo, bienes — todo tiene valor.',
    'community.barter.how1': 'Lista lo que ofreces',
    'community.barter.how2': 'Encuentra lo que necesitas',
    'community.barter.how3': 'Acuerda e intercambia',
    'community.mutual.title': 'Redes de apoyo mutuo',
    'community.mutual.description': 'Conecta con emprendedores que comparten tus valores. Encuentra colaboradores, mentores y clientes que creen en el comercio local.',
    'community.stories.title': 'Historias reales de nuestra comunidad',
    'community.stories.subtitle': 'Personas que cambiaron su forma de vender y conectar',
    'community.story1.quote': '"Empecé vendiendo mermeladas caseras y gracias a JMarkets ahora tengo 200 clientes fieles en mi barrio."',
    'community.story1.name': 'María González',
    'community.story1.business': 'Conservas artesanales · Buenos Aires',
    'community.story2.quote': '"El sistema de trueque me permitió intercambiar diseño gráfico por servicios legales. Eso es economía real — humana y justa."',
    'community.story2.name': 'Carlos Ruiz',
    'community.story2.business': 'Diseñador gráfico · Medellín',
    'community.story3.quote': '"Nuestra cooperativa finalmente tiene presencia digital sin necesitar un programador ni pagar una fortuna."',
    'community.story3.name': 'Ana Morales',
    'community.story3.business': 'Cooperativa agrícola · Oaxaca',
    'community.cta.title': 'Sé parte de la comunidad',
    'community.cta.subtitle': 'Crea tu tienda gratis y conecta con personas que comparten tus valores.',
    'community.cta.button': 'Unirme hoy',

    // Quiénes Somos (About)
    'about.badge': 'Quiénes somos',
    'about.title': 'Nacidos de la comunidad, construidos para la comunidad',
    'about.subtitle': 'JMarkets nació en Guápiles, Costa Rica, como un proyecto universitario comunitario en tiempos de pandemia para reconectar comunidades aisladas a través de sus ferias y redes de trueque.',
    'about.queEs.badge': '¿Qué es JMarkets?',
    'about.queEs.title': 'No solo una tienda — un movimiento',
    'about.queEs.description': 'JMarkets es una plataforma nacida del TCU "Comer Orgánico" de la Universidad de Costa Rica, en alianza con la Feria del Trueque Verde Manantial en Guápiles. Permite a emprendedores, comercios locales y comunidades crear su propio espacio en línea, publicar productos, vender (principalmente por WhatsApp) y participar en ferias y trueques — igual que antes de la pandemia, pero ahora con el alcance de internet.',
    'about.queEs.point1': 'Vende e intercambia productos en tu comunidad',
    'about.queEs.point2': 'Reconecta vecinos que se aislaron durante la pandemia',
    'about.queEs.point3': 'Participa en ferias virtuales, locales y de trueque',
    'about.queEs.point4': 'Preserva y documenta la cultura de ferias comunitarias',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.description': 'Dar a las comunidades las herramientas digitales para mantenerse conectadas, comerciar de forma justa y mantener vivas sus tradiciones de ferias y trueque locales — sin importar lo que el mundo les depare.',
    'about.story.title': 'Nuestra Historia',
    'about.story.para1': 'JMarkets nació durante la pandemia de COVID-19 como parte del TCU (Trabajo Comunal Universitario) "Comer Orgánico" de la Universidad de Costa Rica. Trabajábamos junto a la Feria del Trueque Verde Manantial en Guápiles, Costa Rica — un espacio comunitario vibrante donde la gente se reunía para intercambiar productos, servicios e historias.',
    'about.story.para2': 'Cuando llegó la pandemia, las comunidades quedaron solas y desconectadas. Las ferias que durante años habían unido a las personas enmudecieron. Vimos a vecinos que siempre se encontraban en el mercado ahora sin poder conectarse — y supimos que la tecnología podía ayudar a tender ese puente. Así nació JMarkets: una recreación digital de las ferias que existían antes, diseñada para que la gente pueda mostrar lo que tiene, lo que vende y lo que está dispuesta a trocar.',
    'about.story.para3': 'Desde el principio, documentamos cada paso de este proceso — las necesidades comunitarias, las dinámicas del trueque, los lazos sociales que hacen de una feria algo más que un simple mercado. Esa documentación vive en JMarkets. Hoy este proyecto sigue creciendo como una herramienta para cualquier comunidad que quiera preservar su economía local y mantener a su gente conectada.',
    'about.values.title': 'Nuestros Valores',
    'about.values.fairTrade': 'Comercio Justo',
    'about.values.fairTrade.description': 'Precios justos y condiciones dignas para todos los participantes',
    'about.values.conscious': 'Consumo Consciente',
    'about.values.conscious.description': 'Promovemos decisiones de compra locales y sostenibles',
    'about.values.local': 'Comunidad Local',
    'about.values.local.description': 'Cada compra fortalece la economía local y los lazos del barrio',
    'about.values.transparency': 'Transparencia',
    'about.values.transparency.description': 'Sin cargos ocultos. Abiertos y honestos en cada paso.',
    'about.team.title': 'Un proyecto con raíces comunitarias',
    'about.team.description': 'JMarkets comenzó como un proyecto universitario comunitario y creció hasta convertirse en una plataforma usada por personas reales. Somos investigadores, desarrolladores y defensores de la comunidad que creemos que la tecnología debe servir a las personas — y no al revés.',

    // Página de Ejemplos
    'examples.badge': 'Tiendas de ejemplo',
    'examples.title': 'Elige tu estilo, crea tu espacio',
    'examples.subtitle': 'Explora tiendas creadas con las plantillas de JMarkets. Cada una tiene un diseño único listo para personalizar.',
    'examples.featured': 'Destacada',
    'examples.viewStore': 'Visitar tienda',
    'examples.cta.title': '¿Listo para crear tu propio espacio?',
    'examples.cta.subtitle': 'Empieza gratis, elige tu plantilla y comienza a conectar con tu comunidad hoy.',
    'examples.cta.button': 'Crear mi tienda',
    'examples.stores.demo.title': 'JMarkets Demo',
    'examples.stores.demo.description': 'Tienda de ejemplo completa con productos, carrito de compras, checkout y todas las funcionalidades de la plataforma.',
    'examples.stores.demo.category': 'Demo',
    'examples.stores.bellaNatural.title': 'Tech Gadgets Pro',
    'examples.stores.bellaNatural.description': 'Últimos gadgets y accesorios electrónicos. Smartphones, laptops, tablets y dispositivos innovadores para la vida moderna.',
    'examples.stores.bellaNatural.category': 'Electrónica',
    'examples.stores.glamStudio.title': 'Vintage Fashion Co',
    'examples.stores.glamStudio.description': 'Colección curada de ropa vintage y retro. Piezas únicas de décadas pasadas con estilo atemporal.',
    'examples.stores.glamStudio.category': 'Moda',
    'examples.stores.royalHair.title': 'Artisan Crafts Studio',
    'examples.stores.royalHair.description': 'Manualidades y suministros para DIY. Materiales para tejer, pintar, trabajar la madera y artículos únicos hechos a mano.',
    'examples.stores.royalHair.category': 'Artesanías',
    'examples.stores.skinLove.title': 'Gourmet Foods Market',
    'examples.stores.skinLove.description': 'Alimentos orgánicos y especiales premium. Quesos artesanales, especias exóticas, bebidas artesanales y productos especiales.',
    'examples.stores.skinLove.category': 'Alimentos',
    'examples.stores.proNails.title': 'Fitness Equipment Hub',
    'examples.stores.proNails.description': 'Equipamiento de fitness para hogar y gimnasio. Mancuernas, tapetes de yoga, bandas de resistencia y accesorios de entrenamiento.',
    'examples.stores.proNails.category': 'Deportes',
    'examples.stores.beautySalon.title': 'Pet Care Supplies',
    'examples.stores.beautySalon.description': 'Todo para tus mascotas. Juguetes, productos de aseo, nutrición y camas cómodas para gatos y perros.',
    'examples.stores.beautySalon.category': 'Mascotas',

    // Footer
    'footer.description': 'Plataforma de Economía Social Solidaria para emprendedores, comercios locales y comunidades organizadas.',
    'footer.product': 'Plataforma',
    'footer.company': 'Empresa',
    'footer.legal': 'Legal',
    'footer.links.features': 'Funcionalidades',
    'footer.links.fairs': 'Ferias',
    'footer.links.community': 'Comunidad',
    'footer.links.examples': 'Ejemplos',
    'footer.links.about': 'Quiénes somos',
    'footer.links.contact': 'Contacto',
    'footer.links.blog': 'Blog',
    'footer.links.privacy': 'Privacidad',
    'footer.links.terms': 'Términos',
    'footer.links.cookies': 'Cookies',
    'footer.copyright': '© 2026 JMarkets. Todos los derechos reservados.',

    // Auth
    'auth.login.title': 'JMarkets',
    'auth.login.subtitle': 'Inicia sesión en tu cuenta',
    'auth.login.email': 'Email',
    'auth.login.emailPlaceholder': 'tu@email.com',
    'auth.login.password': 'Contraseña',
    'auth.login.passwordPlaceholder': 'Ingresa tu contraseña',
    'auth.login.submit': 'Iniciar sesión',
    'auth.login.submitting': 'Iniciando sesión...',
    'auth.login.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.login.noAccount': '¿No tienes cuenta?',
    'auth.login.register': 'Regístrate',
    'auth.login.backToHome': 'Volver al inicio',
    'auth.login.success': 'Inicio de sesión exitoso',
    'auth.login.successDescription': 'Bienvenido de vuelta',
    'auth.login.error': 'Error de inicio de sesión',
    'auth.logout': 'Cerrar sesión',
    'auth.register.title': 'Crear cuenta',
    'auth.register.subtitle': 'Comienza a crear tu tienda hoy',
    'auth.register.steps.personalInfo': 'Información Personal',
    'auth.register.steps.personalInfoDesc': 'Información básica',
    'auth.register.steps.security': 'Seguridad',
    'auth.register.steps.securityDesc': 'Crear contraseña',
    'auth.register.steps.verify': 'Verificar',
    'auth.register.steps.verifyDesc': 'Verificación de email',
    'auth.register.firstName': 'Nombre',
    'auth.register.firstNamePlaceholder': 'Tu nombre',
    'auth.register.lastName': 'Apellido',
    'auth.register.lastNamePlaceholder': 'Tu apellido',
    'auth.register.email': 'Email',
    'auth.register.emailPlaceholder': 'tu@email.com',
    'auth.register.username': 'Nombre de usuario',
    'auth.register.usernamePlaceholder': 'usuario123',
    'auth.register.gender': 'Género (opcional)',
    'auth.register.gender.placeholder': 'Selecciona tu género...',
    'auth.register.gender.male': 'Masculino',
    'auth.register.gender.female': 'Femenino',
    'auth.register.gender.other': 'Otro',
    'auth.register.gender.otherPlaceholder': 'Por favor especifica...',
    'auth.register.gender.preferNotToSay': 'Prefiero no decir',
    'auth.register.password': 'Contraseña',
    'auth.register.passwordPlaceholder': 'Crea una contraseña',
    'auth.register.confirmPassword': 'Confirmar contraseña',
    'auth.register.confirmPasswordPlaceholder': 'Confirma tu contraseña',
    'auth.register.continue': 'Continuar',
    'auth.register.back': 'Atrás',
    'auth.register.createAccount': 'Crear cuenta',
    'auth.register.submit': 'Crear cuenta',
    'auth.register.submitting': 'Creando cuenta...',
    'auth.register.hasAccount': '¿Ya tienes cuenta?',
    'auth.register.signIn': 'Inicia sesión',
    'auth.register.login': 'Inicia sesión',
    'auth.register.backToHome': 'Volver al inicio',
    'auth.register.success': 'Cuenta creada',
    'auth.register.successDescription': 'Revisa tu email para verificar tu cuenta',
    'auth.register.complete': 'Registro completo',
    'auth.register.completeDescription': 'Tu cuenta está lista para usar',
    'auth.register.completeStep1': 'Por favor completa el paso 1 primero',
    'auth.register.error': 'Error al crear cuenta',
    'auth.register.passwordMismatch': 'Las contraseñas no coinciden',
    'auth.register.passwordRequirements.minLength': 'Mínimo 8 caracteres',
    'auth.register.passwordRequirements.lowercase': 'Una letra minúscula',
    'auth.register.passwordRequirements.uppercase': 'Una letra mayúscula',
    'auth.register.passwordRequirements.number': 'Un número',
    'auth.register.passwordRequirements.special': 'Un carácter especial',
    'auth.register.passwordStrength.label': 'Fortaleza de Contraseña',
    'auth.register.passwordStrength.weak': 'Débil',
    'auth.register.passwordStrength.fair': 'Regular',
    'auth.register.passwordStrength.good': 'Buena',
    'auth.register.passwordStrength.strong': 'Fuerte',
    'auth.register.passwordStrength.excellent': 'Excelente',
    'auth.forgotPassword.title': '¿Olvidaste tu contraseña?',
    'auth.forgotPassword.subtitle': 'Ingresa tu email y te enviaremos un código de recuperación',
    'auth.forgotPassword.email': 'Email',
    'auth.forgotPassword.emailPlaceholder': 'tu@email.com',
    'auth.forgotPassword.submit': 'Enviar código',
    'auth.forgotPassword.submitting': 'Enviando...',
    'auth.forgotPassword.backToLogin': 'Volver a iniciar sesión',
    'auth.forgotPassword.success': 'Código enviado',
    'auth.forgotPassword.successDescription': 'Revisa tu email para el código de recuperación',
    'auth.forgotPassword.error': 'Error al enviar código',
    'auth.forgotPassword.checkEmail.title': 'Revisa tu email',
    'auth.forgotPassword.checkEmail.subtitle': 'Hemos enviado un código de recuperación a',
    'auth.forgotPassword.checkEmail.enterCode': 'Ingresar código',
    'auth.forgotPassword.checkEmail.differentEmail': 'Usar otro email',
    'auth.resetPassword.title': 'Restablecer contraseña',
    'auth.resetPassword.subtitle': 'Ingresa el código de tu email y tu nueva contraseña',
    'auth.resetPassword.email': 'Email',
    'auth.resetPassword.emailPlaceholder': 'tu@email.com',
    'auth.resetPassword.code': 'Código de recuperación',
    'auth.resetPassword.codePlaceholder': 'Ingresa el código de 6 dígitos',
    'auth.resetPassword.newPassword': 'Nueva contraseña',
    'auth.resetPassword.newPasswordPlaceholder': 'Ingresa tu nueva contraseña',
    'auth.resetPassword.confirmPassword': 'Confirmar contraseña',
    'auth.resetPassword.confirmPasswordPlaceholder': 'Confirma tu nueva contraseña',
    'auth.resetPassword.submit': 'Restablecer contraseña',
    'auth.resetPassword.submitting': 'Restableciendo...',
    'auth.resetPassword.requestNewCode': 'Solicitar nuevo código',
    'auth.resetPassword.backToHome': 'Volver al inicio',
    'auth.resetPassword.success': 'Contraseña restablecida',
    'auth.resetPassword.successDescription': 'Ya puedes iniciar sesión con tu nueva contraseña',
    'auth.resetPassword.error': 'Error al restablecer contraseña',
    'auth.resetPassword.invalidCode': 'Código inválido',
    'auth.resetPassword.invalidCodeDescription': 'El código ingresado es incorrecto',
    'auth.resetPassword.expiredCode': 'Código expirado',
    'auth.resetPassword.expiredCodeDescription': 'Por favor solicita un nuevo código',
    'auth.verifyEmail.title': 'Verifica tu Email',
    'auth.verifyEmail.subtitle': 'Hemos enviado un código de 6 dígitos a',
    'auth.verifyEmail.code': 'Código de verificación',
    'auth.verifyEmail.submit': 'Verificar Email',
    'auth.verifyEmail.submitting': 'Verificando...',
    'auth.verifyEmail.resendCode': 'Reenviar código',
    'auth.verifyEmail.resending': 'Reenviando...',
    'auth.verifyEmail.didntReceive': '¿No recibiste el código?',
    'auth.verifyEmail.success': 'Email verificado',
    'auth.verifyEmail.successDescription': 'Tu cuenta ha sido verificada exitosamente',
    'auth.verifyEmail.error': 'Error de verificación',
    'auth.verifyEmail.resendSuccess': 'Código reenviado',
    'auth.verifyEmail.resendSuccessDescription': 'Hemos enviado un nuevo código de verificación',
    'auth.verifyEmail.invalidCode': 'Código inválido',
    'auth.verifyEmail.invalidCodeDescription': 'Por favor ingresa el código de 6 dígitos',
    'auth.verifyEmail.incorrectCode': 'Código incorrecto',
    'auth.verifyEmail.incorrectCodeDescription': 'El código ingresado no es válido',
    'auth.verifyEmail.expiredCode': 'Código expirado',
    'auth.verifyEmail.expiredCodeDescription': 'El código ha expirado, solicita uno nuevo',
    'auth.verifyEmail.resendError': 'Error',
    'auth.verifyEmail.resendErrorDescription': 'No se pudo reenviar el código',
    'auth.verifyEmail.backToRegister': 'Volver al registro',
    'auth.verifyEmail.alreadyVerified': 'Email ya verificado',
    'auth.verifyEmail.alreadyVerifiedDescription': 'Tu email ya está verificado. Ahora puedes iniciar sesión.',

    // Organizaciones
    'organizations.create.title': 'Crea tu organización',
    'organizations.create.subtitle': 'Configura tu tienda en minutos',
    'organizations.create.name': 'Nombre de la tienda',
    'organizations.create.namePlaceholder': 'Mi Tienda',
    'organizations.create.nameDescription': 'El nombre público de tu tienda',
    'organizations.create.slug': 'URL de la tienda',
    'organizations.create.slugPlaceholder': 'mi-tienda',
    'organizations.create.slugDescription': 'La URL única de tu tienda',
    'organizations.create.subdomain': 'Subdominio',
    'organizations.create.subdomainDescription': 'Tu tienda estará disponible en',
    'organizations.create.submit': 'Crear tienda',
    'organizations.create.submitting': 'Creando tienda...',
    'organizations.create.success': 'Tienda creada',
    'organizations.create.successDescription': 'Tu tienda está lista',
    'organizations.create.error': 'Error al crear tienda',
    'organizations.create.errorAuth': 'Debes iniciar sesión para crear una organización',
    'organizations.create.slugTaken': 'Esta URL ya está en uso',
    'organizations.create.subdomainTaken': 'Este subdominio ya está en uso',
    'organizations.create.checking': 'Verificando disponibilidad...',
    'organizations.select.title': 'Selecciona tu organización',
    'organizations.select.subtitle': 'Elige la tienda que deseas administrar',
    'organizations.select.createNew': 'Crear nueva tienda',
    'organizations.select.noOrganizations': 'No tienes organizaciones',
    'organizations.select.noOrganizationsDescription': 'Crea tu primera tienda para comenzar',
    'organizations.select.loading': 'Cargando organizaciones...',
    'organizations.select.visitStore': 'Visitar tienda',
    'organizations.select.manage': 'Administrar',
    'organizations.select.error': 'No se pudieron cargar tus organizaciones. Por favor, intenta de nuevo.',
    'organizations.select.tryAgain': 'Intentar de nuevo',
    'organizations.select.pendingMessage': 'Completa el aprovisionamiento de organizaciones pendientes antes de crear una nueva.',
    'organizations.select.statusActive': 'Activa',
    'organizations.select.statusPending': 'Pendiente',
    'organizations.select.statusProvisioning': 'Aprovisionando...',
    'organizations.select.statusFailed': 'Fallida',
    'organizations.select.openOrganization': 'Abrir Organización',
    'organizations.select.provisionInfrastructure': 'Aprovisionar Infraestructura',
    'organizations.select.retryProvisioning': 'Reintentar Aprovisionamiento',
    'organizations.select.infrastructureProvisioning': 'La infraestructura se está aprovisionando...',

    // Tema / Idioma
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.system': 'Sistema',
    'language.es': 'Español',
    'language.en': 'English',

    // Blog
    'blog.badge': 'Blog',
    'blog.title': 'Últimas noticias y actualizaciones',
    'blog.subtitle': 'Consejos, guías e información para hacer crecer tu negocio en línea',
    'blog.featured': 'Artículo Destacado',
    'blog.readMore': 'Leer Más',
    'blog.posted': 'Publicado',
    'blog.latestArticles': 'Artículos Más Recientes',
    'blog.stayUpdated': 'Mantente Actualizado',
    'blog.newsletter': 'Suscríbete a nuestro boletín y recibe los últimos artículos, consejos y actualizaciones en tu bandeja de entrada.',
    'blog.subscribe': 'Suscribirse',
    'blog.privacyNote': 'Respetamos tu privacidad. Puedes desuscribirte en cualquier momento.',
    'blog.article1.title': 'Cómo el Trueque Reunió a una Comunidad Tras la Pandemia',
    'blog.article1.excerpt': 'La historia de la Feria del Trueque Verde Manantial en Guápiles — y cómo digitalizarse ayudó a los vecinos a reconectarse cuando las ferias presenciales eran imposibles.',
    'blog.article1.author': 'Equipo JMarkets',
    'blog.article1.date': '15 de enero de 2026',
    'blog.article2.title': '¿Qué es la Economía Social y Solidaria?',
    'blog.article2.excerpt': 'Una introducción a los principios de comercio justo, consumo consciente y construcción de comunidad local que inspiran todo lo que hacemos en JMarkets.',
    'blog.article2.author': 'TCU Comer Orgánico',
    'blog.article2.date': '10 de enero de 2026',
    'blog.article3.title': 'Cómo Crear Tu Espacio Comunitario en JMarkets',
    'blog.article3.excerpt': 'Guía paso a paso para crear tu perfil, publicar tus productos o servicios y conectarte con tu comunidad local.',
    'blog.article3.author': 'Equipo JMarkets',
    'blog.article3.date': '5 de enero de 2026',
    'blog.article4.title': 'Trueque 101: Cómo Hacer Tu Primer Intercambio',
    'blog.article4.excerpt': 'Todo lo que necesitas saber para proponer, negociar y completar un intercambio justo con otro miembro de la comunidad en la plataforma.',
    'blog.article4.author': 'Feria Verde Manantial',
    'blog.article4.date': '28 de diciembre de 2025',
    'blog.article5.title': 'Las Ferias Locales como Infraestructura Comunitaria',
    'blog.article5.excerpt': 'Por qué las ferias comunitarias son mucho más que mercados — son espacios de conexión social, intercambio de conocimientos y resiliencia económica.',
    'blog.article5.author': 'UCR TCU',
    'blog.article5.date': '20 de diciembre de 2025',
    'blog.article6.title': 'Vender por WhatsApp: Consejos para Emprendedores Locales',
    'blog.article6.excerpt': 'Consejos prácticos para gestionar pedidos, comunicarte con compradores y generar confianza por WhatsApp — el canal más usado en nuestra comunidad.',
    'blog.article6.author': 'Equipo JMarkets',
    'blog.article6.date': '12 de diciembre de 2025',

    // Contacto
    'contact.badge': 'Contacto',
    'contact.title': 'Ponte en contacto',
    'contact.subtitle': 'Nos encantaría escucharte. Envíanos un mensaje y te responderemos lo antes posible.',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado exitosamente!',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Teléfono',
    'contact.info.address': 'Dirección',
    'contact.sendMessage': 'Envíanos un mensaje',
    'contact.namePlaceholder': 'Juan Pérez',
    'contact.emailPlaceholder': 'juan@ejemplo.com',
    'contact.subjectPlaceholder': '¿Cómo podemos ayudarte?',
    'contact.messagePlaceholder': 'Tu mensaje aquí...',
    'contact.tryAgain': 'Por favor, inténtalo de nuevo.',
    'contact.otherWays': 'Otras formas de contactarnos',
    'contact.responseTime': 'Tiempo de Respuesta',
    'contact.responseTimeDesc': '¡Generalmente respondemos a todas las consultas dentro de 24 horas durante los días laborales. ¡Gracias por tu paciencia!',

    // Términos
    'terms.badge': 'Términos de Servicio',
    'terms.title': 'Términos y Condiciones',
    'terms.subtitle': 'Por favor, lee estos términos cuidadosamente antes de usar nuestra plataforma comunitaria',
    'terms.lastUpdated': 'Última actualización',
    'terms.section.acceptance': '1. Aceptación de Términos',
    'terms.section.accounts': '2. Cuentas de Usuario',
    'terms.section.services': '3. Descripción de la Plataforma',
    'terms.section.payment': '4. Participación Comunitaria',
    'terms.section.intellectual': '5. Propiedad Intelectual',
    'terms.section.liability': '6. Limitación de Responsabilidad',
    'terms.section.changes': '7. Cambios en los Términos',
    'terms.section.contact': '8. Información de Contacto',
    'terms.acceptance.content': 'Al acceder y utilizar JMarkets, aceptas y te comprometes a cumplir estos términos. JMarkets es una plataforma de Economía Social Solidaria nacida del TCU "Comer Orgánico" de la Universidad de Costa Rica. Si no estás de acuerdo con estos términos, por favor no uses esta plataforma.',
    'terms.accounts.content': 'Eres responsable de mantener la confidencialidad de tus credenciales de cuenta y de todas las actividades realizadas desde tu cuenta. Te comprometes a usar la plataforma de manera respetuosa y acorde con los valores de la comunidad: comercio justo, transparencia y solidaridad.',
    'terms.services.content': 'JMarkets es una plataforma digital para ferias comunitarias, comercio local y trueque. Los usuarios pueden crear su propio espacio, publicar productos y servicios, conectarse con su comunidad y participar en ferias virtuales o locales. La plataforma fue diseñada para preservar y extender la cultura de las ferias comunitarias como la Feria del Trueque Verde Manantial en Guápiles, Costa Rica.',
    'terms.payment.content': 'JMarkets es una plataforma comunitaria. Cualquier transacción, intercambio o acuerdo de trueque entre usuarios es responsabilidad de las partes involucradas. JMarkets actúa como facilitador y no interviene en transacciones privadas entre miembros de la comunidad. Se invita a los usuarios a operar bajo los principios de comercio justo e intercambio honesto.',
    'terms.intellectual.content': 'El contenido publicado por los usuarios en JMarkets sigue siendo propiedad de cada usuario. La plataforma JMarkets en sí — desarrollada como parte del TCU "Comer Orgánico" de la Universidad de Costa Rica — está protegida por las leyes de propiedad intelectual aplicables. Los usuarios otorgan a JMarkets una licencia no exclusiva para mostrar su contenido dentro de la plataforma.',
    'terms.liability.content': 'JMarkets se ofrece como herramienta comunitaria tal cual está. No somos responsables del contenido, productos o servicios ofrecidos por usuarios individuales. Las transacciones y acuerdos entre miembros de la comunidad son responsabilidad exclusiva de las partes involucradas. Animamos a todos los usuarios a interactuar con honestidad y respeto.',
    'terms.changes.content': 'JMarkets se reserva el derecho de actualizar estos términos en cualquier momento. Los usuarios serán notificados de cambios significativos por correo electrónico o aviso destacado en la plataforma. El uso continuado de la plataforma tras los cambios implica la aceptación de los nuevos términos.',
    'terms.contact.content': 'Si tienes preguntas sobre estos términos, contáctanos en hola@jmarkets.com o visita nuestra página de contacto en /contacto.',
    'terms.lastUpdatedDate': '1 de marzo de 2026',
    'terms.importantNotice': 'Compromiso Comunitario',
    'terms.acceptanceNotice': 'Al usar JMarkets, te comprometes a participar en la comunidad con respeto, honestidad y solidaridad. Esta plataforma fue construida para reconectar comunidades — pedimos a cada usuario que honre ese espíritu en cada interacción.',

    // Privacidad
    'privacy.badge': 'Política de Privacidad',
    'privacy.title': 'Política de Privacidad',
    'privacy.subtitle': 'Cómo recopilamos, usamos y protegemos tu información',
    'privacy.lastUpdated': 'Última actualización',
    'privacy.section.information': '1. Información que Recopilamos',
    'privacy.section.usage': '2. Cómo Usamos tu Información',
    'privacy.section.storage': '3. Almacenamiento y Seguridad de Datos',
    'privacy.section.cookies': '4. Cookies y Seguimiento',
    'privacy.section.third': '5. Servicios de Terceros',
    'privacy.section.rights': '6. Tus Derechos',
    'privacy.section.protection': '7. Protección de Datos',
    'privacy.section.contact': '8. Información de Contacto',
    'privacy.information.content': 'Recopilamos información que nos proporcionas directamente, como cuando creas una cuenta, realizas una compra o nos contactas. Esto incluye tu nombre, dirección de correo electrónico, contraseña e información de pago. También recopilamos información automáticamente cuando usas nuestra plataforma, incluyendo datos de registro, cookies e información del dispositivo.',
    'privacy.usage.content': 'Utilizamos tu información para proporcionar, mantener y mejorar nuestros servicios, procesar transacciones, enviar correos electrónicos transaccionales y promocionales, responder a tus consultas y cumplir con obligaciones legales. Utilizamos datos de análisis para entender cómo interactúas con nuestra plataforma y para optimizar la experiencia del usuario.',
    'privacy.storage.content': 'Tus datos se almacenan en servidores seguros con tecnología de cifrado. Implementamos salvaguardas físicas, electrónicas y procedimentales apropiadas para proteger tu información contra acceso, alteración, divulgación o destrucción no autorizados. Sin embargo, ningún método de transmisión a través de Internet es completamente seguro.',
    'privacy.cookies.content': 'Utilizamos cookies y tecnologías de seguimiento similares para rastrear la actividad en nuestra plataforma y retener cierta información. Puedes instruir a tu navegador para rechazar todas las cookies o para alertarte cuando se envíe una cookie. Sin embargo, algunas características de la plataforma pueden no funcionar correctamente sin cookies.',
    'privacy.third.content': 'Podemos compartir tu información con proveedores de servicios de terceros que nos ayudan a operar nuestra plataforma y conducir nuestro negocio. Estos proveedores están obligados contractualmente a usar tu información solo según sea necesario para proporcionarnos servicios.',
    'privacy.rights.content': 'Dependiendo de tu ubicación, puedes tener ciertos derechos con respecto a tus datos personales, incluido el derecho a acceder, corregir, eliminar o transferir tu información. Para ejercer cualquiera de estos derechos, contáctanos en privacy@jmarkets.com.',
    'privacy.protection.content': 'Cumplimos con las regulaciones de protección de datos aplicables, incluyendo el GDPR y leyes similares. Mantenemos salvaguardas apropiadas para proteger tus datos y solo retenemos información por el tiempo necesario para proporcionar nuestros servicios y cumplir con obligaciones legales.',
    'privacy.contact.content': 'Si tienes preguntas sobre esta política de privacidad o nuestras prácticas de privacidad, contáctanos en privacy@jmarkets.com o visita nuestra página de contacto. Estamos comprometidos a trabajar contigo para resolver cualquier preocupación sobre privacidad.',
    'privacy.lastUpdatedDate': '1 de enero de 2026',
    'privacy.notice': 'Tu Privacidad es Importante',
    'privacy.noticeDesc': 'Estamos comprometidos a proteger tu privacidad y asegurar que tengas una experiencia positiva en nuestra plataforma. Si tienes preguntas sobre cómo manejamos tus datos, no dudes en contactarnos.',

    // Cookies
    'cookies.badge': 'Política de Cookies',
    'cookies.title': 'Política de Cookies',
    'cookies.subtitle': 'Información sobre cómo utilizamos las cookies',
    'cookies.what': '¿Qué son las Cookies?',
    'cookies.types': 'Tipos de Cookies',
    'cookies.essential': 'Cookies Esenciales',
    'cookies.essential.description': 'Necesarias para la funcionalidad básica',
    'cookies.analytics': 'Cookies de Análisis',
    'cookies.analytics.description': 'Nos ayudan a entender cómo usas nuestra plataforma',
    'cookies.marketing': 'Cookies de Marketing',
    'cookies.marketing.description': 'Se utilizan para personalizar contenido y anuncios',
    'cookies.preferences': 'Cookies de Preferencia',
    'cookies.preferences.description': 'Recuerdan tus opciones y configuración',
    'cookies.manage': 'Gestionar Preferencias de Cookies',
    'cookies.explanation': 'Las cookies son pequeños archivos de texto que se almacenan en tu dispositivo cuando visitas un sitio web. Ayudan a los sitios web a recordar información sobre tu visita, como tus preferencias y actividad. Las cookies pueden ser esenciales para la funcionalidad básica del sitio web o se pueden usar para mejorar la experiencia del usuario a través del seguimiento y personalización.',
    'cookies.browser': 'La mayoría de navegadores web te permiten controlar las cookies a través de su configuración. Puedes elegir aceptar todas las cookies, rechazar todas o ser notificado cuando se establezca una cookie.',
    'cookies.usingBrowser': 'Usando tu Navegador',
    'cookies.usingBrowserDesc': 'La mayoría de navegadores modernos incluyen herramientas de gestión de cookies en su configuración. Generalmente puedes encontrarlas bajo "Privacidad" o configuración de "Seguridad". Diferentes navegadores (Chrome, Firefox, Safari, Edge) tienen diferentes procesos, pero todos te permiten ver, eliminar y gestionar cookies.',
    'cookies.consent': 'Consentimiento de Cookies',
    'cookies.consentDesc': 'Cuando visitas JMarkets por primera vez, mostramos un banner de consentimiento de cookies. Puedes aceptar todas las cookies, rechazar las no esenciales o personalizar tus preferencias. Puedes cambiar tus preferencias de cookies en cualquier momento a través de la configuración de tu cuenta.',
    'cookies.third': 'Cookies de Terceros',
    'cookies.thirdDesc': 'Algunas cookies pueden ser establecidas por servicios de terceros (como proveedores de análisis). Estos servicios tienen sus propias políticas de privacidad y opciones de gestión de cookies. A menudo puedes gestionar estas preferencias a través del sitio web del tercero.',
    'cookies.important': 'Nota Importante',
    'cookies.importantDesc': 'Deshabilitar las cookies esenciales puede afectar la funcionalidad de nuestra plataforma. Recomendamos mantener las cookies esenciales habilitadas para garantizar la mejor experiencia. Las cookies no esenciales se pueden deshabilitar sin afectar la funcionalidad principal.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved) return saved;
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('es') ? 'es' : 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
